name: "Build One by One (anyone)"
on:
  workflow_dispatch:
    inputs:

      armbian_target:
        type: choice
        description: 'Build'
        required: false
        options:
        - kernel
        - build
        default: build

      armbian_kernel_branch:
        type: choice
        description: 'Kernel branch'
        options:
        - legacy
        - current
        - edge
        default: 'current'

      armbian_release:
        type: choice
        description: 'Userspace'
        options:
        - jammy
        - mantic
        - bookworm
        - trixie
        - bullseye
        - noble
        - buster
        - sid
        default: 'noble'

      armbian_ui:
        type: choice
        description: 'User interface (not all works)'
        options:
        - minimal
        - server
        - xfce
        - gnome
        - cinnamon
        - i3-wm
        - kde-plasma
        default: 'server'

      armbian_version:
        description: 'Version'
        required: false
        default: ''

      armbian_board:
        type: choice
        description: 'Board'
        options:
        - bananapi
        - bananapicm4io
        - bananapif3
        - bananapim1plus
        - bananapim2plus
        - bananapim2pro
        - bananapim2s
        - bananapim2ultra
        - bananapim2zero
        - bananapim3
        - bananapim4zero
        - bananapim5
        - bananapim64
        - bananapim7
        - bananapipro
        - bananapir2
        - bananapir2pro
        
jobs:

  build:
    name: "Build Armbian"
    runs-on: ubuntu-latest
    steps:

      - uses: armbian/build@main
        with:
          armbian_token:              "${{secrets.GITHUB_TOKEN}}"
          armbian_target:             "${{inputs.armbian_target}}"
          armbian_release:            "${{inputs.armbian_release}}"
          armbian_kernel_branch:      "${{inputs.armbian_kernel_branch}}"
          armbian_ui:                 "${{inputs.armbian_ui}}"
          armbian_board:              "${{inputs.armbian_board}}"
          armbian_release_tittle:     "Armbian SDK"
          armbian_release_body:       "Virtual images for x86 and arm64"
          armbian_pgp_key:            "${{secrets.GPG_KEY1}}"
          armbian_pgp_password:       "${{secrets.GPG_PASSPHRASE1}}"
