name: Build Armbian
on:
  workflow_dispatch:
    inputs:
      BOARD:
        description: 'Target board (e.g., orangepizero3)'
        required: true
      BRANCH:
        description: 'Kernel branch (e.g., edge)'
        required: true
      RELEASE:
        description: 'Release Name: '
        required: false
        default: 'jammy'
      BUILD_MINIMAL:
        description: 'Build minimal environment (yes/no)'
        required: false
        default: 'yes'
      BUILD_DESKTOP:
        description: 'Desktop environment y/n'
        required: false
        default: 'no'
      KERNEL:
        description: 'Kernel version (e.g., 5.10.63-1)'
        required: false
        default: 'yes'
      KERNEL_CONFIGURE:
        description: 'Kernel configuration (e.g., arm64_defconfig)'
        required: false
        default: 'no'
      

jobs:
  build-armbian:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Clone Armbian repository
        uses: armbian/build@v24.11.0-trunk.368
      - name: Set environment variables
        env:
          ARMBIAN_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BOARD: ${{ github.event.inputs.BOARD }}
          BRANCH: ${{ github.event.inputs.BRANCH }}
          RELEASE: ${{ github.event.inputs.RELEASE }}
          BUILD_MINIMAL: ${{ github.event.inputs.BUILD_MINIMAL }}
          BUILD_DESKTOP: ${{ github.event.inputs.BUILD_DESKTOP }}
          KERNEL: ${{ github.event.inputs.KERNEL }}
          KERNEL_CONFIGURE: ${{ github.event.inputs.KERNEL_CONFIGURE }}
      - name: Build Armbian image
        run: |
          ./compile.sh build \
            BOARD=$BOARD \
            BRANCH=$BRANCH \
            RELEASE=$RELEASE \
            BUILD_MINIMAL=$BUILD_MINIMAL \
            BUILD_DESKTOP=$BUILD_DESKTOP \
            KERNEL=$KERNEL \
            KERNEL_CONFIGURE=$KERNEL_CONFIGURE 
      - name: Upload built image
        uses: actions/upload-artifact@v2
        with:
          name: armbian-image
          path: output/image.img
          
