name: Armbian Build

on:
  push:
    branches:
      - main

jobs:
  build-armbian:
    runs-on: self-hosted-arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Armbian
        run: |
          docker run -it --rm -v $(pwd):/build armbian/buildx:latest
      - name: Push built image
        uses: docker/build-push-action@v2
          username: ${{ secrets."hexzhen3x7" }}
          password: ${{ secrets."MultiV3rz3X3!?" }}
          repository: ${{ github.repository }}
          tag: ${{ github.sha }}
